[TSK-268] utilizing scraped data from pipeline to create a jupyter notebook in kubeflow and doing some basic analysis
dream-aim-deliver/planckster-docs pull request #23
Opened 2024-08-05 21:39 UTC by sk-ram

2024-08-07 20:32 UTC, ydamit requested changes
Generally looks close to being ready, but there are a few changes that might be important to make this easier to understand and digest.

2024-08-07 20:32 UTC, ydamit commented on docs/guides/kubeflow/analysing-scraped-data.md
> +            download_source_if_relevant(source, job_id, tracer_id, scraped_data_repository, work_dir)
Also, `work_dir` shows up enough throughout this code that it's probably worth defining it somewhere here or earlier - even if it's just a placeholder they're supposed to fill in.

2024-08-07 20:32 UTC, ydamit commented on docs/guides/kubeflow/analysing-scraped-data.md
> +                data.append([f"tweet about {tweet_disaster_type}", tweet_latitude, tweet_longitude, tweet_title, tweet_tweet, tweet_location ])
Check indentation

2024-08-07 20:32 UTC, ydamit commented on docs/guides/kubeflow/analysing-scraped-data.md
> +            # match sattelite image dates with tweet dates
```suggestion
            # match satellite image dates with tweet dates
```

2024-08-07 20:32 UTC, ydamit commented on docs/guides/kubeflow/analysing-scraped-data.md
> +# load the sattelite image dates
```suggestion
# load the satellite image dates
```

2024-08-09 12:23 UTC, maany commented
Merging! Looks like @sk-ram has addressed the comments from @ydamit

2024-08-09 12:23 UTC, merged